"""
Word / DOCX design report builder — ALLL WPS Designer.

Produces a stamped engineering memorandum with:
  - Title page with project metadata, stamp block, and revision table
  - Executive summary
  - System description / basis of design
  - Hydraulic calculations (Darcy-Weisbach equations, head budget, system curve)
  - Pump analysis (H-Q / η / P / NPSHr curves, operating points, VFD)
  - Wet well sizing and pump cycling (AWWA M32)
  - Engineering checks summary
  - Surge / water hammer analysis (Joukowsky + MOC + protection comparison)
  - Appendices: full inputs, pump curve data table, surge time-series snapshot,
                pipe roughness reference

Figures are generated by backend.engine.word_figures and embedded as PNGs.
"""

from __future__ import annotations

import io
import math
from datetime import date as _date
from typing import Any

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor

from backend.engine.word_figures import (
    fig_efficiency_power,
    fig_moc_histories,
    fig_npsh,
    fig_protection_comparison,
    fig_surge_envelope_discharge,
    fig_surge_envelope_suction,
    fig_system_curve,
)

# ---------------------------------------------------------------------------
# Colour palette
# ---------------------------------------------------------------------------

NAVY  = RGBColor(0x1F, 0x38, 0x64)
TEAL  = RGBColor(0x1A, 0x52, 0x76)
GREY  = RGBColor(0x4A, 0x4A, 0x4A)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)

FIGURE_WIDTH_IN = 5.8  # default embedded figure width [in]


# ---------------------------------------------------------------------------
# Unit conversion helpers
# ---------------------------------------------------------------------------

def _us(unit_system: str, val: float | None, kind: str) -> tuple[float | None, str]:
    """Convert SI value → display unit. Returns (converted_val, unit_label)."""
    if val is None:
        return None, "—"
    if unit_system != "US":
        labels = {
            "flow": "m³/h", "head": "m", "pressure": "kPa",
            "velocity": "m/s", "length": "m", "volume": "m³",
            "power": "kW", "temp": "°C",
        }
        return val, labels.get(kind, "—")
    conv = {
        "flow":     (val * 4.40287,      "gpm"),
        "head":     (val * 3.28084,      "ft"),
        "pressure": (val * 0.14504,      "psi"),
        "velocity": (val * 3.28084,      "ft/s"),
        "length":   (val * 3.28084,      "ft"),
        "volume":   (val * 264.172,      "gal"),
        "power":    (val * 1.34102,      "hp"),
        "temp":     (val * 9 / 5 + 32,   "°F"),
    }
    return conv.get(kind, (val, "—"))


def _fmt(val: float | None, dp: int = 2) -> str:
    if val is None:
        return "—"
    return f"{val:,.{dp}f}"


# ---------------------------------------------------------------------------
# Low-level XML helpers
# ---------------------------------------------------------------------------

def _set_cell_shading(cell, hex_color: str) -> None:
    tc   = cell._tc
    tcPr = tc.get_or_add_tcPr()
    shd  = OxmlElement("w:shd")
    shd.set(qn("w:val"),   "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"),  hex_color)
    tcPr.append(shd)


def _set_cell_borders(cell, color: str = "BBBBBB") -> None:
    tc      = cell._tc
    tcPr    = tc.get_or_add_tcPr()
    tcBords = OxmlElement("w:tcBorders")
    for side in ("top", "left", "bottom", "right"):
        el = OxmlElement(f"w:{side}")
        el.set(qn("w:val"),   "single")
        el.set(qn("w:sz"),    "4")
        el.set(qn("w:color"), color)
        tcBords.append(el)
    tcPr.append(tcBords)


def _add_page_numbers(doc: Document) -> None:
    """
    Insert « Page X of Y » centre-aligned in every section footer.
    Uses Word's built-in PAGE and NUMPAGES fields.
    """
    for section in doc.sections:
        footer         = section.footer
        footer.is_linked_to_previous = False
        fp = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
        fp.clear()
        fp.alignment = WD_ALIGN_PARAGRAPH.CENTER

        run_pre = fp.add_run("Page ")
        run_pre.font.size = Pt(8)

        # PAGE field
        fld_page = OxmlElement("w:fldChar")
        fld_page.set(qn("w:fldCharType"), "begin")
        fp.runs[-1]._r.append(fld_page)

        instr = OxmlElement("w:instrText")
        instr.text = " PAGE "
        fp.runs[-1]._r.append(instr)

        end_page = OxmlElement("w:fldChar")
        end_page.set(qn("w:fldCharType"), "end")
        fp.runs[-1]._r.append(end_page)

        run_of = fp.add_run(" of ")
        run_of.font.size = Pt(8)

        # NUMPAGES field
        fld_total = OxmlElement("w:fldChar")
        fld_total.set(qn("w:fldCharType"), "begin")
        fp.runs[-1]._r.append(fld_total)

        instr2 = OxmlElement("w:instrText")
        instr2.text = " NUMPAGES "
        fp.runs[-1]._r.append(instr2)

        end_total = OxmlElement("w:fldChar")
        end_total.set(qn("w:fldCharType"), "end")
        fp.runs[-1]._r.append(end_total)


# ---------------------------------------------------------------------------
# High-level document helpers
# ---------------------------------------------------------------------------

def _heading(doc: Document, text: str, level: int = 1) -> None:
    p   = doc.add_heading(text, level=level)
    run = p.runs[0] if p.runs else p.add_run(text)
    if level == 1:
        run.font.color.rgb = NAVY
        run.font.size      = Pt(14)
    elif level == 2:
        run.font.color.rgb = TEAL
        run.font.size      = Pt(12)
    else:
        run.font.color.rgb = GREY
        run.font.size      = Pt(11)


def _para(doc: Document, text: str, bold: bool = False,
          italic: bool = False, size: int = 10) -> None:
    p   = doc.add_paragraph()
    run = p.add_run(text)
    run.bold   = bold
    run.italic = italic
    run.font.size = Pt(size)


def _equation(doc: Document, text: str) -> None:
    """Render an equation-style paragraph in Courier New 8 pt, indented."""
    p   = doc.add_paragraph()
    p.paragraph_format.left_indent = Inches(0.4)
    run = p.add_run(text)
    run.font.name  = "Courier New"
    run.font.size  = Pt(8)
    run.font.color.rgb = RGBColor(0x33, 0x33, 0x33)


def _hline(doc: Document) -> None:
    """Insert a thin horizontal rule via paragraph border."""
    p    = doc.add_paragraph()
    pPr  = p._p.get_or_add_pPr()
    pBdr = OxmlElement("w:pBdr")
    bot  = OxmlElement("w:bottom")
    bot.set(qn("w:val"),   "single")
    bot.set(qn("w:sz"),    "6")
    bot.set(qn("w:color"), "1F3864")
    pBdr.append(bot)
    pPr.append(pBdr)


def _page_break(doc: Document) -> None:
    doc.add_page_break()


def _kv_table(doc: Document, rows: list[tuple[str, str]],
              col_widths: tuple[float, float] = (2.5, 3.5)) -> None:
    """Compact 2-column key-value table with navy key cells."""
    if not rows:
        return
    tbl = doc.add_table(rows=len(rows), cols=2)
    tbl.style = "Table Grid"
    for i, (k, v) in enumerate(rows):
        key_c = tbl.rows[i].cells[0]
        val_c = tbl.rows[i].cells[1]
        key_c.text = k
        val_c.text = str(v)
        for run in key_c.paragraphs[0].runs:
            run.bold           = True
            run.font.size      = Pt(9)
        for run in val_c.paragraphs[0].runs:
            run.font.size = Pt(9)
        _set_cell_shading(key_c, "D0E4F5")
        _set_cell_borders(key_c)
        _set_cell_borders(val_c)
        key_c.width = Inches(col_widths[0])
        val_c.width = Inches(col_widths[1])


def _col_table(doc: Document, headers: list[str],
               data_rows: list[list[str]],
               col_widths: list[float] | None = None) -> None:
    """Multi-column data table with navy header row."""
    if not data_rows:
        return
    n_cols = len(headers)
    tbl    = doc.add_table(rows=1 + len(data_rows), cols=n_cols)
    tbl.style = "Table Grid"

    hdr_row = tbl.rows[0]
    for j, h in enumerate(headers):
        c = hdr_row.cells[j]
        c.text = h
        for run in c.paragraphs[0].runs:
            run.bold           = True
            run.font.size      = Pt(9)
            run.font.color.rgb = WHITE
        _set_cell_shading(c, "1F3864")
        _set_cell_borders(c)
        if col_widths:
            c.width = Inches(col_widths[j])

    for i, dr in enumerate(data_rows):
        bg  = "F2F5F8" if i % 2 == 1 else "FFFFFF"
        row = tbl.rows[i + 1]
        for j, val in enumerate(dr):
            c = row.cells[j]
            c.text = str(val)
            for run in c.paragraphs[0].runs:
                run.font.size = Pt(9)
            _set_cell_shading(c, bg)
            _set_cell_borders(c)


def _embed_figure(doc: Document, fig_bytes: bytes, caption: str = "",
                  width_in: float = FIGURE_WIDTH_IN) -> None:
    """Embed a PNG byte string as a centred figure with optional caption."""
    buf = io.BytesIO(fig_bytes)
    p   = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.add_run().add_picture(buf, width=Inches(width_in))
    if caption:
        cap = doc.add_paragraph(caption)
        cap.alignment = WD_ALIGN_PARAGRAPH.CENTER
        if cap.runs:
            cap.runs[0].italic    = True
            cap.runs[0].font.size = Pt(9)


# ---------------------------------------------------------------------------
# Title page (including revision table)
# ---------------------------------------------------------------------------

def _title_page(doc: Document, meta: dict) -> None:
    doc.add_paragraph()
    doc.add_paragraph()

    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    tr = title.add_run("ALLL WPS DESIGNER")
    tr.bold           = True
    tr.font.size      = Pt(22)
    tr.font.color.rgb = NAVY

    sub = doc.add_paragraph()
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sr = sub.add_run("Pump Station Design Report")
    sr.font.size      = Pt(16)
    sr.font.color.rgb = TEAL

    doc.add_paragraph()
    _hline(doc)
    doc.add_paragraph()

    # Document stamp block
    stamp_rows: list[tuple[str, str]] = [
        ("Project",   meta.get("name",      "—")),
        ("Client",    meta.get("client",     "—")),
        ("Job No.",   meta.get("job_number", "—")),
        ("Date",      meta.get("date",       str(_date.today()))),
        ("Engineer",  meta.get("engineer",   "—")),
        ("Status",    "Preliminary"),
    ]
    _kv_table(doc, stamp_rows, col_widths=(2.0, 4.0))

    doc.add_paragraph()

    # Revision table — Rev 0 baseline row
    rev_headers = ["Rev", "Date", "Description", "Prepared by", "Checked by"]
    rev_rows    = [
        ["0",
         meta.get("date", str(_date.today())),
         "Preliminary issue for review",
         meta.get("engineer", "—"),
         "—"],
    ]
    _col_table(doc, rev_headers, rev_rows,
               col_widths=[0.4, 1.0, 2.6, 1.2, 1.0])

    if meta.get("notes"):
        doc.add_paragraph()
        _para(doc, "Design Notes:", bold=True)
        _para(doc, meta["notes"])

    _page_break(doc)


# ---------------------------------------------------------------------------
# Section 1 — Executive Summary
# ---------------------------------------------------------------------------

def _executive_summary(doc: Document, draft: dict) -> None:
    _heading(doc, "1. Executive Summary")

    meta  = draft.get("meta",              {}) or {}
    hyd   = draft.get("hydraulicsResult") or {}
    pump  = draft.get("pumpResult")        or {}
    cw    = draft.get("clearwellResult")   or {}
    surge = draft.get("waterHammerResult") or {}
    us    = draft.get("unitSystem", "SI")
    Q     = draft.get("designFlow_m3h", 0) or 0

    _para(doc, (
        f"This report documents the engineering design calculations for the pump station "
        f"project '{meta.get('name', 'unnamed')}'. "
        f"The design flow is {_fmt(Q, 1)} m³/h. "
        f"The system has been assessed for hydraulic adequacy, pump selection, "
        f"wet well capacity, and surge protection."
    ))
    doc.add_paragraph()

    rows: list[tuple[str, str]] = []

    if hyd:
        q_v,   q_u   = _us(us, Q,                        "flow")
        tdh_v, tdh_u = _us(us, hyd.get("tdh_m"),         "head")
        rows += [
            ("Design Flow",         f"{_fmt(q_v, 1)} {q_u}"),
            ("Total Dynamic Head",  f"{_fmt(tdh_v)} {tdh_u}"),
            ("Pipe Velocity",       f"{_fmt(hyd.get('velocity_ms'), 3)} m/s"),
            ("Friction Head Loss",  f"{_fmt(hyd.get('friction_head_m'))} m"),
        ]

    ops = pump.get("operating_points", []) if pump else []
    if ops:
        op = ops[0]
        rows += [
            ("Pump Duty Q",         f"{_fmt(op.get('Q_m3h'))} m³/h"),
            ("Pump Duty H",         f"{_fmt(op.get('H_m'))} m"),
            ("Pump Efficiency",     f"{_fmt(op.get('eta_pct'), 1)} %"),
            ("Shaft Power",         f"{_fmt(op.get('power_kW'))} kW"),
            ("NPSH Margin",         f"{_fmt(op.get('npsh_margin_m'))} m"),
        ]

    if cw and cw.get("active"):
        rows += [
            ("Operating Volume",    f"{_fmt(cw.get('operating_volume_m3'))} m³"),
            ("Detention Time",      f"{_fmt(cw.get('detention_time_min'), 1)} min"),
        ]

    if surge:
        cav = surge.get("cavitation_risk", False)
        rows += [
            ("Joukowsky ΔH",        f"{_fmt(surge.get('delta_H_joukowsky_m'))} m"),
            ("Max Surge Head",      f"{_fmt(surge.get('max_pressure_head_m'))} m"),
            ("Cavitation Risk",     "YES — mitigation required" if cav else "No"),
        ]

    if rows:
        _kv_table(doc, rows)

    doc.add_paragraph()


# ---------------------------------------------------------------------------
# Section 2 — System Description
# ---------------------------------------------------------------------------

def _system_description(doc: Document, draft: dict) -> None:
    _heading(doc, "2. System Description")

    us    = draft.get("unitSystem", "SI")
    Q     = draft.get("designFlow_m3h", 0) or 0
    up    = draft.get("upstreamNode",   {}) or {}
    dn    = draft.get("downstreamNode", {}) or {}
    suct  = draft.get("suction",        {}) or {}
    disc  = draft.get("discharge",      {}) or {}

    static = dn.get("elevation_m", 0) - up.get("elevation_m", 0)
    q_v, q_u = _us(us, Q, "flow")
    hs_v, hs_u = _us(us, static, "head")

    _para(doc, (
        f"The pump station transfers {_fmt(q_v, 1)} {q_u} of potable water against a "
        f"static head of {_fmt(hs_v)} {hs_u}. "
        f"The suction side is at elevation {_fmt(up.get('elevation_m'), 2)} m and the "
        f"discharge is at elevation {_fmt(dn.get('elevation_m'), 2)} m above datum."
    ))

    s_segs = suct.get("segments", []) or []
    d_segs = disc.get("segments", []) or []
    s_len  = sum(s.get("length_m", 0) for s in s_segs)
    d_len  = sum(s.get("length_m", 0) for s in d_segs)
    s_mats = ", ".join(sorted({s.get("material", "").upper() for s in s_segs if s.get("material")}))
    d_mats = ", ".join(sorted({s.get("material", "").upper() for s in d_segs if s.get("material")}))

    doc.add_paragraph()
    _para(doc, (
        f"The suction pipeline comprises {len(s_segs)} segment(s) totalling {_fmt(s_len, 1)} m "
        f"of pipe (material: {s_mats or '—'}, ΣK = {_fmt(suct.get('accessories_K_sum', 0), 3)}). "
        f"The discharge pipeline comprises {len(d_segs)} segment(s) totalling {_fmt(d_len, 1)} m "
        f"(material: {d_mats or '—'}, ΣK = {_fmt(disc.get('accessories_K_sum', 0), 3)})."
    ))
    doc.add_paragraph()


# ---------------------------------------------------------------------------
# Section 3 — Basis of Design
# ---------------------------------------------------------------------------

def _basis_of_design(doc: Document, draft: dict) -> None:
    _heading(doc, "3. Basis of Design")
    _heading(doc, "3.1 Design Parameters", level=2)

    us  = draft.get("unitSystem", "SI")
    Q   = draft.get("designFlow_m3h", 0) or 0
    up  = draft.get("upstreamNode",   {}) or {}
    dn  = draft.get("downstreamNode", {}) or {}

    q_v,  q_u  = _us(us, Q,                                     "flow")
    hs_v, hs_u = _us(us, dn.get("elevation_m", 0) - up.get("elevation_m", 0), "head")

    rows = [
        ("Design flow Q",            f"{_fmt(q_v, 1)} {q_u}"),
        ("Suction node elevation",   f"{_fmt(up.get('elevation_m'), 2)} m"),
        ("Discharge node elevation", f"{_fmt(dn.get('elevation_m'), 2)} m"),
        ("Static head",              f"{_fmt(hs_v)} {hs_u}"),
        ("Unit system",              us),
    ]
    _kv_table(doc, rows)
    doc.add_paragraph()

    _heading(doc, "3.2 Pipeline Configuration", level=2)

    for side in ("suction", "discharge"):
        assy  = draft.get(side, {}) or {}
        segs  = assy.get("segments", []) or []
        k_sum = assy.get("accessories_K_sum", 0.0) or 0.0

        _para(doc, f"{side.capitalize()} — {len(segs)} segment(s), ΣK = {_fmt(k_sum, 3)}",
              bold=True)
        if segs:
            headers   = ["#", "Material", "Diameter (mm)", "Length (m)"]
            data_rows = [
                [str(i + 1),
                 s.get("material", "—").upper(),
                 _fmt(s.get("diameter_mm"), 0),
                 _fmt(s.get("length_m"), 1)]
                for i, s in enumerate(segs)
            ]
            _col_table(doc, headers, data_rows, col_widths=[0.3, 1.8, 1.5, 1.5])
        doc.add_paragraph()


# ---------------------------------------------------------------------------
# Section 4 — Hydraulic Analysis
# ---------------------------------------------------------------------------

def _hydraulics_section(doc: Document, draft: dict) -> None:
    _heading(doc, "4. Hydraulic Analysis")

    us  = draft.get("unitSystem", "SI")
    Q   = draft.get("designFlow_m3h", 0) or 0
    hyd = draft.get("hydraulicsResult") or {}

    _heading(doc, "4.1 Friction Loss Method", level=2)
    _para(doc, (
        "Friction head losses are computed using the Darcy-Weisbach equation with "
        "the Colebrook-White implicit friction factor, iterated to convergence. "
        "Minor losses are calculated as ΣK·V²/(2g). "
        "Hazen-Williams coefficients are applied where specified per segment."
    ))
    doc.add_paragraph()

    _heading(doc, "4.2 Key Equations", level=2)
    _para(doc, "Darcy-Weisbach friction head loss:", bold=True)
    _equation(doc, "hf = f · (L / D) · V² / (2g)")
    _para(doc, "Colebrook-White (implicit, iterated):", bold=True)
    _equation(doc, "1/√f = −2 log₁₀( ε/(3.7·D)  +  2.51/(Re·√f) )")
    _para(doc, "Reynolds number:", bold=True)
    _equation(doc, "Re = ρ·V·D / μ      [turbulent if Re > 4000]")
    _para(doc, "Minor head loss:", bold=True)
    _equation(doc, "hm = ΣK · V² / (2g)")
    _para(doc, "Total Dynamic Head:", bold=True)
    _equation(doc, "TDH = Hs + ΣHf + ΣHm + ΔHpressure + ΔHvelocity")
    doc.add_paragraph()

    if not hyd:
        _para(doc, "Hydraulic compute not yet run — results not available.", italic=True)
        return

    _heading(doc, "4.3 Head Budget", level=2)

    q_v,   q_u   = _us(us, Q,                          "flow")
    vel_v, vel_u  = _us(us, hyd.get("velocity_ms"),    "velocity")
    hs_v,  hs_u   = _us(us, hyd.get("static_head_m"), "head")
    hf_v,  hf_u   = _us(us, hyd.get("friction_head_m"), "head")
    hm_v,  hm_u   = _us(us, hyd.get("minor_head_m"),  "head")
    tdh_v, tdh_u  = _us(us, hyd.get("tdh_m"),         "head")

    rows = [
        ("Design flow Q",           f"{_fmt(q_v, 1)} {q_u}"),
        ("Pipe velocity V",         f"{_fmt(vel_v, 3)} {vel_u}"),
        ("Reynolds number Re",      f"{(hyd.get('reynolds_number') or 0):,.0f}"),
        ("Darcy friction factor f", _fmt(hyd.get("friction_factor"), 5)),
        ("Static head Hs",          f"{_fmt(hs_v)} {hs_u}"),
        ("Friction head Hf",        f"{_fmt(hf_v)} {hf_u}"),
        ("Minor head Hm",           f"{_fmt(hm_v)} {hm_u}"),
        ("Total Dynamic Head TDH",  f"{_fmt(tdh_v)} {tdh_u}  ← design duty"),
    ]
    _kv_table(doc, rows)
    doc.add_paragraph()

    sys_pts = hyd.get("system_curve", []) or []
    if sys_pts:
        _heading(doc, "4.4 System Curve Data Points", level=2)
        headers   = ["Q (m³/h)", "H (m)"]
        data_rows = [[_fmt(p.get("Q_m3h"), 1), _fmt(p.get("H_m"))] for p in sys_pts]
        _col_table(doc, headers, data_rows, col_widths=[1.5, 1.5])
        doc.add_paragraph()

    fig_bytes = fig_system_curve(draft, us=us)
    if fig_bytes:
        _embed_figure(doc, fig_bytes,
                      "Figure 1 — Pump H-Q and system curve overlay with duty operating point(s)")
    doc.add_paragraph()


# ---------------------------------------------------------------------------
# Section 5 — Pump Analysis
# ---------------------------------------------------------------------------

def _pump_section(doc: Document, draft: dict) -> None:
    _heading(doc, "5. Pump Analysis")

    pump = draft.get("pumpResult") or {}
    us   = draft.get("unitSystem", "SI")

    if not pump or not pump.get("active"):
        _para(doc, "Pump analysis not activated.", italic=True)
        return

    _heading(doc, "5.1 Operating Points", level=2)

    ops = pump.get("operating_points", []) or []
    if ops:
        headers = [
            "Pumps", "Q (m³/h)", "H (m)", "η (%)", "P (kW)",
            "NPSHr (m)", "NPSHa (m)", "Margin (m)", "Warnings",
        ]
        data_rows = []
        for op in ops:
            q_v, _ = _us(us, op.get("Q_m3h"), "flow")
            h_v, _ = _us(us, op.get("H_m"),   "head")
            data_rows.append([
                str(op.get("n_pumps", 1)),
                _fmt(q_v),
                _fmt(h_v),
                _fmt(op.get("eta_pct"), 1),
                _fmt(op.get("power_kW")),
                _fmt(op.get("npshr_m")),
                _fmt(op.get("npsha_m")),
                _fmt(op.get("npsh_margin_m")),
                "; ".join(op.get("warnings", [])) or "None",
            ])
        _col_table(doc, headers, data_rows,
                   col_widths=[0.5, 0.8, 0.7, 0.6, 0.7, 0.8, 0.8, 0.8, 1.5])
        doc.add_paragraph()

    _heading(doc, "5.2 Performance Curves", level=2)

    hq_pts  = pump.get("hq_curve",    []) or []
    eta_pts = pump.get("eta_curve",   []) or []
    p_pts   = pump.get("p_curve",     []) or []
    npshr   = pump.get("npshr_curve", []) or []

    if hq_pts:
        headers   = ["Q (m³/h)", "H (m)", "η (%)", "P (kW)", "NPSHr (m)"]
        data_rows = []
        for i, hp in enumerate(hq_pts):
            eta_val  = eta_pts[i].get("value") if i < len(eta_pts) else None
            p_val    = p_pts[i].get("value")   if i < len(p_pts)   else None
            nr_val   = npshr[i].get("value")   if i < len(npshr)   else None
            data_rows.append([
                _fmt(hp.get("Q_m3h"), 1),
                _fmt(hp.get("value")),
                _fmt(eta_val, 1),
                _fmt(p_val),
                _fmt(nr_val),
            ])
        _col_table(doc, headers, data_rows,
                   col_widths=[1.0, 1.0, 1.0, 1.0, 1.0])
        doc.add_paragraph()

    sp_curves = pump.get("speed_curves", []) or []
    if sp_curves:
        _heading(doc, "5.3 Variable Frequency Drive — Affinity Law Curves", level=2)
        _para(doc, "Affinity laws at reduced speed N/N_rated:")
        _equation(doc, "Q ∝ N     H ∝ N²     P ∝ N³")
        doc.add_paragraph()

    fig_eff = fig_efficiency_power(draft)
    if fig_eff:
        _embed_figure(doc, fig_eff,
                      "Figure 2 — Pump efficiency η (%) and shaft power P (kW) vs flow")

    fig_npsh_bytes = fig_npsh(draft)
    if fig_npsh_bytes:
        _embed_figure(doc, fig_npsh_bytes,
                      "Figure 3 — NPSHr (required) and NPSHa (available) vs flow")
    doc.add_paragraph()

    warnings = list(pump.get("warnings", []) or [])
    if pump.get("non_physical_fit"):
        warnings.insert(0, "Non-physical polynomial fit — curve data may be insufficient.")
    if warnings:
        _para(doc, "Pump Analysis Warnings:", bold=True)
        for w in warnings:
            _para(doc, f"  • {w}")
        doc.add_paragraph()


# ---------------------------------------------------------------------------
# Section 6 — Wet Well Sizing
# ---------------------------------------------------------------------------

def _wetwell_section(doc: Document, draft: dict) -> None:
    _heading(doc, "6. Wet Well Sizing and Pump Cycling")

    cw = draft.get("clearwellResult") or {}
    us = draft.get("unitSystem", "SI")

    if not cw or not cw.get("active"):
        _para(doc, "Wet well analysis not activated.", italic=True)
        return

    _heading(doc, "6.1 Key Results", level=2)

    op_v, op_u = _us(us, cw.get("operating_volume_m3"), "volume")
    rows = [
        ("Operating volume (LWL → HWL)",    f"{_fmt(op_v)} {op_u}"),
        ("Detention time",                   f"{_fmt(cw.get('detention_time_min'), 1)} min"),
        ("Required detention",               f"{_fmt(cw.get('required_detention_min'), 1)} min"),
        ("Detention OK",                     "Yes" if cw.get("detention_ok") else "No / Not checked"),
    ]
    _kv_table(doc, rows)
    doc.add_paragraph()

    cr_list = cw.get("cycle_results", []) or []
    if cr_list:
        _heading(doc, "6.2 Pump Cycle Analysis (AWWA M32)", level=2)
        headers = [
            "Stage", "Label", "Q pump (m³/h)", "Q in (m³/h)",
            "t drain (s)", "t cycle (s)", "Cycles/hr", "OK",
        ]
        data_rows = []
        for cr in cr_list:
            data_rows.append([
                str(cr.get("stage", "")),
                cr.get("label", ""),
                _fmt(cr.get("Q_pump_m3h"), 1),
                _fmt(cr.get("Q_in_m3h"),  1),
                _fmt(cr.get("t_drain_s"), 0),
                _fmt(cr.get("t_cycle_s"), 0),
                _fmt(cr.get("cycles_per_hour"), 2),
                "Yes" if cr.get("cycles_ok") else "No",
            ])
        _col_table(doc, headers, data_rows,
                   col_widths=[0.5, 1.0, 1.0, 1.0, 0.9, 0.9, 0.8, 0.5])
        doc.add_paragraph()

    vol_curve = cw.get("volume_curve", []) or []
    if vol_curve:
        _heading(doc, "6.3 Volume Curve", level=2)
        headers   = ["Level (m)", "Depth (m)", "Volume (m³)"]
        data_rows = [
            [_fmt(p.get("level_m")), _fmt(p.get("depth_m")), _fmt(p.get("volume_m3"))]
            for p in vol_curve
        ]
        _col_table(doc, headers, data_rows, col_widths=[1.5, 1.5, 1.5])
        doc.add_paragraph()

    for w in cw.get("warnings", []) or []:
        _para(doc, f"  ⚠ {w}")
    doc.add_paragraph()


# ---------------------------------------------------------------------------
# Section 7 — Engineering Checks
# ---------------------------------------------------------------------------

def _engineering_checks_section(doc: Document, draft: dict) -> None:
    _heading(doc, "7. Engineering Checks")

    hyd  = draft.get("hydraulicsResult") or {}
    pump = draft.get("pumpResult")       or {}
    cw   = draft.get("clearwellResult")  or {}
    us   = draft.get("unitSystem", "SI")

    checks: list[tuple[str, str, str]] = []

    if hyd:
        vel = hyd.get("velocity_ms", 0) or 0
        vel_v, vel_u = _us(us, vel, "velocity")
        v_ok = 0.5 <= vel <= 3.0
        checks.append(("Pipe velocity", f"{_fmt(vel_v, 3)} {vel_u}",
                        "OK" if v_ok else "WARNING"))

        re = hyd.get("reynolds_number", 0) or 0
        checks.append(("Reynolds number", f"{re:,.0f}",
                        "OK" if re > 4000 else "INFO"))

    ops = pump.get("operating_points", []) if pump else []
    for op in ops:
        margin = op.get("npsh_margin_m")
        if margin is not None:
            sev = "OK" if margin >= 0.6 else ("WARNING" if margin >= 0 else "CRITICAL")
            checks.append((f"NPSH margin (n={op.get('n_pumps', 1)})",
                            f"{_fmt(margin)} m", sev))
        eta = op.get("eta_pct")
        if eta is not None:
            checks.append((f"Pump efficiency (n={op.get('n_pumps', 1)})",
                            f"{_fmt(eta, 1)} %", "OK" if eta >= 60 else "WARNING"))

    if cw and cw.get("active"):
        for cr in cw.get("cycle_results", []) or []:
            s = "OK" if cr.get("cycles_ok") else "WARNING"
            checks.append((f"Pump cycles — {cr.get('label', '')}",
                            f"{_fmt(cr.get('cycles_per_hour'), 2)} /hr", s))
        dt_ok = cw.get("detention_ok")
        if dt_ok is not None:
            checks.append(("Detention time",
                            f"{_fmt(cw.get('detention_time_min'), 1)} min",
                            "OK" if dt_ok else "WARNING"))

    if not checks:
        _para(doc, "No checks available — run analyses first.", italic=True)
        return

    COLOR_MAP = {"OK": "27AE60", "WARNING": "F39C12", "CRITICAL": "E74C3C", "INFO": "2980B9"}
    tbl = doc.add_table(rows=1 + len(checks), cols=3)
    tbl.style = "Table Grid"

    for j, h in enumerate(["Parameter", "Value", "Status"]):
        c = tbl.rows[0].cells[j]
        c.text = h
        for run in c.paragraphs[0].runs:
            run.bold           = True
            run.font.size      = Pt(9)
            run.font.color.rgb = WHITE
        _set_cell_shading(c, "1F3864")
        _set_cell_borders(c)

    for i, (param, val, status) in enumerate(checks):
        row = tbl.rows[i + 1]
        row.cells[0].text = param
        row.cells[1].text = val
        row.cells[2].text = status
        bg = "F2F5F8" if i % 2 == 1 else "FFFFFF"
        for cell in row.cells:
            for run in cell.paragraphs[0].runs:
                run.font.size = Pt(9)
            _set_cell_borders(cell)
            _set_cell_shading(cell, bg)
        status_c = row.cells[2]
        _set_cell_shading(status_c, COLOR_MAP.get(status, "FFFFFF"))
        if status != "OK":
            for run in status_c.paragraphs[0].runs:
                run.bold           = True
                run.font.color.rgb = WHITE

    doc.add_paragraph()


# ---------------------------------------------------------------------------
# Section 8 — Surge / Water Hammer Analysis
# ---------------------------------------------------------------------------

def _surge_section(doc: Document, draft: dict) -> None:
    _heading(doc, "8. Surge / Water Hammer Analysis")

    surge = draft.get("waterHammerResult") or {}
    moc   = draft.get("mocResult")         or {}
    wi    = draft.get("whatIfResult")      or {}

    # 8.1 Joukowsky
    _heading(doc, "8.1 Joukowsky Instantaneous Analysis (Mode A)", level=2)
    _para(doc, (
        "The Joukowsky equation gives the maximum pressure rise for an "
        "instantaneous pump trip or valve closure (conservative upper bound):"
    ))
    _equation(doc, "ΔH = a · ΔV / g")
    doc.add_paragraph()

    if surge:
        rows = [
            ("Wave speed a",           f"{_fmt(surge.get('wave_speed_ms'), 0)} m/s"),
            ("Initial velocity V₀",    f"{_fmt(surge.get('V0_ms'), 3)} m/s"),
            ("Joukowsky ΔH",           f"{_fmt(surge.get('delta_H_joukowsky_m'))} m"),
            ("Joukowsky ΔP",           f"{_fmt(surge.get('delta_P_joukowsky_kPa'), 0)} kPa"),
            ("Operating head H₀",      f"{_fmt(surge.get('H_operating_m'))} m"),
            ("Max transient head",     f"{_fmt(surge.get('max_pressure_head_m'))} m"),
            ("Min transient head",     f"{_fmt(surge.get('min_pressure_head_m'))} m"),
            ("Cavitation risk",        "YES" if surge.get("cavitation_risk") else "No"),
            ("Vacuum risk",            "YES" if surge.get("vacuum_risk")     else "No"),
            ("Characteristic time Tc", f"{_fmt(surge.get('T_char_s'), 3)} s"),
        ]
        _kv_table(doc, rows)
        doc.add_paragraph()
    else:
        _para(doc, "Surge quick analysis not run.", italic=True)

    # 8.2 MOC
    if moc:
        _heading(doc, "8.2 Method of Characteristics — Full Transient Simulation", level=2)
        _para(doc, (
            "The Method of Characteristics (MOC) solves the 1D transient pipe-flow "
            "PDEs on a characteristic grid, capturing wave reflections, attenuation, "
            "and node-by-node pressure histories."
        ))
        _equation(doc, "∂H/∂t + (a²/g)·∂V/∂x = 0    and    ∂V/∂t + g·∂H/∂x + f·V|V|/(2D) = 0")
        doc.add_paragraph()

        rows = [
            ("Pipe segments N",        str(moc.get("N", "—"))),
            ("Spatial step Δx",        f"{_fmt(moc.get('dx_m'))} m"),
            ("Time step Δt",           f"{_fmt(moc.get('dt_s'), 4)} s"),
            ("Courant number",         f"{_fmt(moc.get('courant'), 3)}"),
            ("Simulation duration",    f"{_fmt(moc.get('t_total_s'), 1)} s"),
            ("Global max head H_max",  f"{_fmt(moc.get('global_max_H_m'))} m"),
            ("Global min head H_min",  f"{_fmt(moc.get('global_min_H_m'))} m"),
            ("Cavitation locations",   str(len(moc.get("cavitation_x_m", []) or []))),
        ]
        _kv_table(doc, rows)
        doc.add_paragraph()

        fig_suct = fig_surge_envelope_suction(draft)
        if fig_suct:
            _embed_figure(doc, fig_suct,
                          "Figure 4a — MOC pressure envelope: suction pipeline")

        fig_disc = fig_surge_envelope_discharge(draft)
        if fig_disc:
            _embed_figure(doc, fig_disc,
                          "Figure 4b — MOC pressure envelope: discharge pipeline")

        fig_hist = fig_moc_histories(draft)
        if fig_hist:
            _embed_figure(doc, fig_hist,
                          "Figure 5 — MOC head time histories at key observation nodes")

        doc.add_paragraph()

        obs = moc.get("observations", []) or []
        if obs:
            _heading(doc, "8.3 Time History Summary at Key Nodes", level=2)
            headers = ["Node", "x (m)", "H max (m)", "H min (m)"]
            data_rows = []
            for ob in obs:
                hist   = ob.get("history", []) or []
                h_vals = [h.get("H_m", 0) for h in hist]
                data_rows.append([
                    ob.get("label", ""),
                    _fmt(ob.get("x_m")),
                    _fmt(max(h_vals) if h_vals else None),
                    _fmt(min(h_vals) if h_vals else None),
                ])
            _col_table(doc, headers, data_rows, col_widths=[2.0, 1.0, 1.2, 1.2])
            doc.add_paragraph()

    # 8.4 Protection comparison
    if wi and (wi.get("baseline") or wi.get("device_runs")):
        _heading(doc, "8.4 Surge Protection Device Comparison", level=2)

        baseline = wi.get("baseline") or {}
        runs     = wi.get("device_runs", []) or []
        headers  = ["Scenario", "H max (m)", "H min (m)", "ΔH reduction (m)", "Cavitation"]
        data_rows = []
        for r in [baseline] + runs:
            data_rows.append([
                r.get("label", "Baseline"),
                _fmt(r.get("global_max_H_m")),
                _fmt(r.get("global_min_H_m")),
                _fmt(r.get("max_surge_reduction_m")),
                "Yes" if r.get("cavitation_risk") else "No",
            ])
        _col_table(doc, headers, data_rows, col_widths=[2.0, 1.0, 1.0, 1.2, 1.0])
        doc.add_paragraph()

        fig_prot = fig_protection_comparison(draft)
        if fig_prot:
            _embed_figure(doc, fig_prot,
                          "Figure 6 — Surge protection: peak pressure comparison by device")

        for n in wi.get("assumption_notes", []) or []:
            _para(doc, f"  • {n}")
        doc.add_paragraph()


# ---------------------------------------------------------------------------
# Appendix A — Complete Input Parameters
# ---------------------------------------------------------------------------

def _appendix_inputs(doc: Document, draft: dict) -> None:
    _page_break(doc)
    _heading(doc, "Appendix A — Complete Input Parameters")

    meta  = draft.get("meta", {}) or {}
    up    = draft.get("upstreamNode",   {}) or {}
    dn    = draft.get("downstreamNode", {}) or {}

    rows = [
        ("Project name",     meta.get("name",      "—")),
        ("Client",           meta.get("client",     "—")),
        ("Job number",       meta.get("job_number", "—")),
        ("Date",             meta.get("date",       "—")),
        ("Engineer",         meta.get("engineer",   "—")),
        ("Unit system",      draft.get("unitSystem", "SI")),
        ("Design flow",      f"{_fmt(draft.get('designFlow_m3h'), 1)} m³/h"),
        ("Upstream elev.",   f"{_fmt(up.get('elevation_m'), 2)} m"),
        ("Downstream elev.", f"{_fmt(dn.get('elevation_m'), 2)} m"),
    ]
    _kv_table(doc, rows)
    doc.add_paragraph()

    for side in ("suction", "discharge"):
        assy = draft.get(side, {}) or {}
        segs = assy.get("segments", []) or []
        _para(doc, f"{side.capitalize()} segments:", bold=True)
        if segs:
            headers   = ["#", "Material", "Ø (mm)", "L (m)"]
            data_rows = [
                [str(i + 1),
                 s.get("material", ""),
                 _fmt(s.get("diameter_mm"), 0),
                 _fmt(s.get("length_m"), 1)]
                for i, s in enumerate(segs)
            ]
            _col_table(doc, headers, data_rows, col_widths=[0.3, 2.0, 1.0, 1.0])
        doc.add_paragraph()


# ---------------------------------------------------------------------------
# Appendix B — Pump Curve Data Table
# ---------------------------------------------------------------------------

def _appendix_pump_curves(doc: Document, draft: dict) -> None:
    _heading(doc, "Appendix B — Full Pump Curve Data Table")

    pump    = draft.get("pumpResult") or {}
    hq_pts  = pump.get("hq_curve",    []) or []
    eta_pts = pump.get("eta_curve",   []) or []
    p_pts   = pump.get("p_curve",     []) or []
    npshr   = pump.get("npshr_curve", []) or []

    if not hq_pts:
        _para(doc, "Pump curve data not available — run pump analysis first.", italic=True)
        return

    headers   = ["Point", "Q (m³/h)", "H (m)", "η (%)", "P (kW)", "NPSHr (m)"]
    data_rows = []
    for i, hp in enumerate(hq_pts):
        eta_val = eta_pts[i].get("value") if i < len(eta_pts) else None
        p_val   = p_pts[i].get("value")   if i < len(p_pts)   else None
        nr_val  = npshr[i].get("value")   if i < len(npshr)   else None
        data_rows.append([
            str(i + 1),
            _fmt(hp.get("Q_m3h"), 1),
            _fmt(hp.get("value")),
            _fmt(eta_val, 1),
            _fmt(p_val),
            _fmt(nr_val),
        ])
    _col_table(doc, headers, data_rows,
               col_widths=[0.5, 1.0, 1.0, 1.0, 1.0, 1.0])
    doc.add_paragraph()

    # Speed curves (VFD)
    sp_curves = pump.get("speed_curves", []) or []
    for sc in sp_curves:
        spd  = sc.get("speed_pct", "?")
        pts  = sc.get("hq_pts", []) or []
        if pts:
            _para(doc, f"VFD Speed Step — {spd}% rated speed:", bold=True)
            sc_rows = [
                [_fmt(p.get("Q_m3h"), 1), _fmt(p.get("value", p.get("H_m", 0)))]
                for p in pts
            ]
            _col_table(doc, ["Q (m³/h)", "H (m)"], sc_rows, col_widths=[1.5, 1.5])
            doc.add_paragraph()


# ---------------------------------------------------------------------------
# Appendix C — Surge Time-Series Snapshot
# ---------------------------------------------------------------------------

def _appendix_surge_timeseries(doc: Document, draft: dict) -> None:
    _heading(doc, "Appendix C — Surge Time-Series Snapshot (first 50 rows per node)")

    moc = draft.get("mocResult") or {}
    obs = moc.get("observations", []) or []

    if not obs:
        _para(doc, "MOC time-series data not available.", italic=True)
        return

    for ob in obs:
        label = ob.get("label", "Node")
        hist  = ob.get("history", []) or []

        _para(doc, f"Observation: {label}  (x = {_fmt(ob.get('x_m'))} m)", bold=True)

        if not hist:
            _para(doc, "  No time history data.", italic=True)
            doc.add_paragraph()
            continue

        snapshot = hist[:50]
        headers  = ["t (s)", "H (m)", "P (kPa)"]
        data_rows= [
            [_fmt(h.get("t_s"), 3), _fmt(h.get("H_m")), _fmt(h.get("P_kPa"), 1)]
            for h in snapshot
        ]
        _col_table(doc, headers, data_rows, col_widths=[1.2, 1.2, 1.2])

        if len(hist) > 50:
            _para(doc, f"  … {len(hist) - 50} further row(s) omitted.", italic=True)
        doc.add_paragraph()


# ---------------------------------------------------------------------------
# Appendix D — Pipe Roughness Reference
# ---------------------------------------------------------------------------

def _appendix_roughness_ref(doc: Document) -> None:
    _heading(doc, "Appendix D — Pipe Roughness Reference")

    headers   = ["Material", "Roughness ε (m)", "Typical HW-C"]
    data_rows = [
        ["PVC / HDPE / uPVC",  "0.0000015", "150"],
        ["Ductile iron (DICL)", "0.000250",  "130"],
        ["Steel (unlined)",     "0.000046",  "120"],
        ["Asbestos cement",     "0.000030",  "140"],
        ["Concrete",            "0.000300",  "110"],
        ["GRP / FRP",           "0.000030",  "150"],
    ]
    _col_table(doc, headers, data_rows, col_widths=[2.5, 1.8, 1.5])
    doc.add_paragraph()


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def build_document(draft: dict) -> Document:
    """
    Build a full engineering Word report from a ProjectDraft dict.

    Parameters
    ----------
    draft : dict
        Serialised ProjectDraft — same payload used by the Excel exporter.

    Returns
    -------
    docx.Document
        Fully populated python-docx Document object.
    """
    draft = draft or {}
    meta  = draft.get("meta", {}) or {}

    doc = Document()

    # Page margins
    for section in doc.sections:
        section.top_margin    = Inches(1.0)
        section.bottom_margin = Inches(1.0)
        section.left_margin   = Inches(1.2)
        section.right_margin  = Inches(1.2)

    # Footer with page numbers
    _add_page_numbers(doc)

    # Title page (stamp + revision table)
    _title_page(doc, meta)

    # Body sections
    _executive_summary(doc, draft)
    _system_description(doc, draft)
    _basis_of_design(doc, draft)
    _hydraulics_section(doc, draft)
    _pump_section(doc, draft)
    _wetwell_section(doc, draft)
    _engineering_checks_section(doc, draft)
    _surge_section(doc, draft)

    # Appendices
    _appendix_inputs(doc, draft)
    _appendix_pump_curves(doc, draft)
    _appendix_surge_timeseries(doc, draft)
    _appendix_roughness_ref(doc)

    return doc


def _doc_to_bytes(doc: Document) -> bytes:
    """Serialise a Document to a .docx byte string."""
    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()
